- name: Checkout
  uses: actions/checkout@v2
 
- name: Set up Python Env
  uses: actions/setup-python@v1
  with:
    python-version: 3.10.14      

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install arxiv
    pip install requests

- name: Configure git to trust the directory
  run: git config --global --add safe.directory /github/workspace

- name: Run daily arxiv 
  run: python .github/0802arXivAPI2.py

- name: Push new cv-arxiv-daily.md
  uses: github-actions-x/commit@v2.8
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    commit-message: "Github Action Automatic Update CV Arxiv Papers"
    files: README.md cv-arxiv-daily.json
    rebase: 'true'
    name: ${{ env.GITHUB_USER_NAME }}
    email: ${{ env.GITHUB_USER_EMAIL }}
